// Server Component — no 'use client' needed

// ── Types ──────────────────────────────────────────────────────────

interface WeeklyReportCardProps {
  /** 2-3 sentence Oracle weekly summary */
  summary: string;
  /** Formatted date string, e.g. "April 7, 2026" */
  weekOf: string;
}

// ── Oracle "O" glyph ──────────────────────────────────────────────

function OracleGlyph() {
  return (
    <div className="w-7 h-7 rounded-lg bg-oracle-teal/10 border border-oracle-teal/20 flex items-center justify-center shrink-0">
      <span className="font-display font-bold text-oracle-teal text-sm leading-none select-none">
        O
      </span>
    </div>
  );
}

// ── Main component ─────────────────────────────────────────────────

export function WeeklyReportCard({ summary, weekOf }: WeeklyReportCardProps) {
  return (
    <div className="oracle-card p-6 h-full flex flex-col">

      {/* ── Header ─────────────────────────────────────────────── */}
      <div className="flex items-start justify-between mb-6 gap-4">
        <div>
          <p className="oracle-label mb-1.5">Oracle Weekly Report</p>
          <h2 className="font-display text-xl font-semibold text-oracle-bright">
            Your Week in Focus
          </h2>
        </div>
        <div className="text-right shrink-0">
          <p className="oracle-label">Week of</p>
          <p className="font-mono text-xs text-oracle-text mt-0.5 whitespace-nowrap">{weekOf}</p>
        </div>
      </div>

      {/* ── Teal-bordered summary block ─────────────────────────── */}
      <div className="border-l-2 border-oracle-teal pl-5 flex-1">
        <p className="text-oracle-text text-base italic leading-relaxed">
          &ldquo;{summary}&rdquo;
        </p>
      </div>

      {/* ── Attribution footer ───────────────────────────────────── */}
      <div className="mt-6 pt-5 border-t border-oracle-border flex items-center gap-2.5">
        <OracleGlyph />
        <p className="oracle-label text-[10px] leading-relaxed">
          Generated by Oracle AI &middot; Synthesised from your email, calendar, finance &amp; health data
        </p>
      </div>

    </div>
  );
}
